### ISSUE TITLE
Verificar qual  modelo de classificação de imagens já existe pode ser usado no projeto.

### ISSUE THREAD

**Issue by mardntas** [machine-learning-2020-2-Kedelai/kedelaiApp#2]

**Comment by Jonathan-Oliveira** [comment]
Na [documentação do pytorch](https://pytorch.org/vision/stable/models.html) há alguns modelos pré-treinados que podem ser utilizados na nossa aplicação. 
Fazendo uma pesquisa encontrei um [artigo](https://www.sciencedirect.com/science/article/abs/pii/S0168169919322422) que resolve um problema semelhante ao nosso e foi utilizado o VGGNet e o modelo Inception na abordagem deles.
